logging:
  level:
    root: INFO
---
server:
  port: 8080
  servlet:
    context-path: /baseServices
---
keycloak:
  enabled: true
  bearer-only: true
  #auth-server-url: https://portal.ecuasanitas.com/auth-test
  #desarrollo externo
  #auth-server-url: https://portal.ecuasanitas.com/auth-test
  #desarrollo interno
  auth-server-url: http://192.168.40.151:8080/auth

  #resource: e-voucher-client-core
  #resource: BASE-WEB
  resource: farmaenlace-ws
  #realm: luca-realm
  #realm: SSO-NOVO
  realm: xtn
  public-client: true
  principal-attribute: preferred_username
  # credentials:
  # secret: 123
  use-resource-role-mappings: false
  allowAnyHostname: true
  ssl-required: external
  realm-key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAsKLLU93WgIHHz0iR/RCO68BFO9BUVqA2gLCIT8cnefOazaS1WlZdtPVE7oEUCzZsWMd/cJlWh8aVteSvOX1G7rwxnABv4jQZf1DZ8x6zY4CGhj8rhkDLyFJXLwRkUIdJ8QsY0w9zBkR9wHZwOgeHxkUzod+dhymkDI9LVu8y8bSMokCD82yiOYMiBjTLyCioNiwc3IdljCxa+l2gMGDhCe7bHKVvwVec5bN1fVU/CNR3Gh15zi1e3NKyEMNkaDspGxpHgIRHF+WBqgKVxoTfquwmAcC6D/Pnc9V2ldOk5O3n1TriDq+2zPDIp9XeLI3GQ789ia1ntNIwguls6iLlgwIDAQAB

---
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driverClassName: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@192.168.40.24:1521/bdd1.ecuasanitas.com
    username: NOVO
    password: NOVO
    hikari:
      connectionTimeout: 60000
      idleTimeout: 600000
      maxLifetime: 1800000
      maximumPoolSize: 20
      #connectionTestQuery: CALL NOW()
  jpa:
    showSql: true
    properties:
      format_sql: false
      hibernate:
        dialect: org.hibernate.dialect.Oracle10gDialect
        #        dialect: org.hibernate.dialect.PostgreSQLDialect
        #        dialect: org.hibernate.dialect.MariaDB103Dialect
        id:
          batch_versioned_data: true
          new_generator_mappings: false # true for increment by 50 or (allocationSize property in mapping), false for increment one by one
        jdbc:
          batch_size: 50
          batch_versioned_data: true
        order_inserts: true
        order_updates: true
        generate_statistics: false

